#!/bin/bash

#---------------------------------------------------------
# Set the shell path. Avoid duplicates
#---------------------------------------------------------
add_to_path() {
    if [[ -d "$1" ]] && [[ ":$PATH:" != *":$1:"* ]]; then
        export PATH="$PATH:$1"
    fi
}
add_to_path "$HOME/pablo-common/bin"
add_to_path "$HOME/pablo-common/scripts"
add_to_path "$HOME/moos-ivp/bin"
add_to_path "$HOME/moos-ivp/scripts"
add_to_path "$HOME/moos-ivp-heron/bin"
add_to_path "$HOME/moos-ivp-blueboat/bin"
add_to_path "$HOME/moos-ivp-swarm/bin"
add_to_path "$HOME/moos-ivp-pavlab/bin"
add_to_path "$HOME/moos-ivp-multi/bin"

#---------------------------------------------------------
# Set IVP_BEHAVIOR_DIRS. Avoid duplicates
#---------------------------------------------------------
add_to_bdir() {
    if [[ -d "$1" ]] && [[ ":$IVP_BEHAVIOR_DIRS:" != *":$1:"* ]]; then
        export IVP_BEHAVIOR_DIRS="$IVP_BEHAVIOR_DIRS:$1"
    fi
}
add_to_bdir "$HOME/moos-ivp/lib"
add_to_bdir "$HOME/moos-ivp-pavlab/lib"
add_to_bdir "$HOME/moos-ivp-swarm/lib"
add_to_bdir "$HOME/moos-ivp-2680/lib"
add_to_bdir "$HOME/moos-ivp-multi/lib"
   
#---------------------------------------------------------
# Add ssh authorized keys
#---------------------------------------------------------
IN_SSH_KEYS=$PABLO_DIR/pablo_authorized_keys
TARG_SSH_KEYS=~/.ssh/authorized_keys
$PABLO_DIR/bin/copy_no_duplicates.sh $IN_SSH_KEYS $TARG_SSH_KEYS

#---------------------------------------------------------
# Get Temperature function for RasPIs
#---------------------------------------------------------
function getTemperature() {
  if [ -x "$(command -v vcgencmd)" ]; then
    # The following regex gets the first group of numbers longer than
    # 2 digits
    TEMP=`vcgencmd measure_temp | grep -oE '([0-9]+){2,}'`
    if [ $TEMP -ge 70 ]; then
      RESET=`tput sgr0`
      RED=`tput setaf 1`
      TEMP="${RED}${TEMP}"
    fi
    echo "${TEMP}°"
    unset RESET RED
  fi
}
