#!/bin/bash

#---------------------------------------------------------
# MOOS-IvP Settings
#---------------------------------------------------------
PATH=$PATH:~/moos-ivp/bin
PATH=$PATH:~/moos-ivp/scripts
PATH=$PATH:~/moos-ivp-heron/bin
PATH=$PATH:~/moos-ivp-blueboat/bin
PATH=$PATH:~/moos-ivp-swarm/bin
PATH=$PATH:~/moos-ivp-pavlab/bin
PATH=$PATH:~/moos-ivp-multi/bin

IVP_BEHAVIOR_DIRS=$IVP_BEHAVIOR_DIRS:$HOME/moos-ivp/lib
IVP_BEHAVIOR_DIRS+=:$HOME/moos-ivp-pavlab/lib
IVP_BEHAVIOR_DIRS+=:$HOME/moos-ivp-swarm/lib
IVP_BEHAVIOR_DIRS+=:$HOME/moos-ivp-2680/lib
IVP_BEHAVIOR_DIRS+=:$HOME/moos-ivp-multi/lib
export IVP_BEHAVIOR_DIRS
   

#---------------------------------------------------------
# pablo-common Settings
#---------------------------------------------------------
export PABLO_DIR=$HOME/pablo-common

# General pablo-common
PATH=$PATH:$PABLO_DIR/bin

#---------------------------------------------------------
# Add ssh authorized keys
#---------------------------------------------------------
IN_SSH_KEYS=$PABLO_DIR/pablo_authorized_keys
TARG_SSH_KEYS=~/.ssh/authorized_keys
$PABLO_DIR/bin/copy_no_duplicates.sh $IN_SSH_KEYS $TARG_SSH_KEYS

#---------------------------------------------------------
# Get Temperature function for RasPIs
#---------------------------------------------------------
function getTemperature() {
  if [ -x "$(command -v vcgencmd)" ]; then
    # The following regex gets the first group of numbers longer than
    # 2 digits
    TEMP=`vcgencmd measure_temp | grep -oE '([0-9]+){2,}'`
    if [ $TEMP -ge 70 ]; then
      RESET=`tput sgr0`
      RED=`tput setaf 1`
      TEMP="${RED}${TEMP}"
    fi
    echo "${TEMP}°"
    unset RESET RED
  fi
}
